global using System.IO;
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using Image = System.Windows.Controls.Image;
global using TextBox = System.Windows.Controls.TextBox;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using Color = System.Windows.Media.Color;
global using Brushes = System.Windows.Media.Brushes;
global using Point = System.Windows.Point;
global using Size = System.Windows.Size;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using Cursors = System.Windows.Input.Cursors;
global using Orientation = System.Windows.Controls.Orientation;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using MessageBox = System.Windows.MessageBox;
